ajax/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sample.urls'))
]

sample/urls.py
from django.urls import path
from . import views

app_name = 'sample'

urlpatterns = [
    # トップ画面
    path('', views.IndexView.as_view(), name='index'),

    # 詳細画面
    path('sample/<int:pk>/', views.DetailView.as_view(), name='detail'),

    # Ajax処理
    path("sample/<int:pk>/exec/", views.exec_ajax, name='exec'),
    path("sample/<int:pk>/exec_another/", views.exec_another_ajax, name='exec_another'),
]

sample/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime as dt


class Location(models.Model):
    """場所モデル"""
    class Meta:
        db_table = 'location'

    name = models.CharField(verbose_name='ロケーション名', max_length=255)
    memo = models.CharField(verbose_name='メモ', max_length=255, default='', blank=True)
    created_at = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url(self):
        return reverse('sample:index')


class WeatherData(models.Model):
    """気象データモデル"""
    class Meta:
        db_table = 'weather_data'
        unique_together = (('location', 'data_datetime'),)

    location = models.ForeignKey(Location, verbose_name='ロケーション', on_delete=models.PROTECT)
    data_datetime = models.DateTimeField(verbose_name='データ日時', default=dt.strptime('2001-01-01 00:00:00', '%Y-%m-%d %H:%M:%S'))
    temperature = models.FloatField(verbose_name='気温')
    humidity = models.FloatField(verbose_name='湿度')
    created_at = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    def __str__(self):
        return self.location.name + ":" + str(self.data_datetime)

sample/views.py
from django.http import HttpResponse
from django.views import generic
from .models import Location, WeatherData
import logging


logger = logging.getLogger('development')


class IndexView(generic.ListView):
    model = Location
    paginate_by = 5
    ordering = ['-updated_at']
    template_name = 'sample/index.html'


class DetailView(generic.DetailView):
    model = Location
    template_name = 'sample/detail.html'


def exec_ajax(request, pk):

    if request.method == 'GET':  # GETの処理
        param1 = request.GET.get("param1")  # GETパラメータ1
        param2 = request.GET.get("param2")  # GETパラメータ2
        param3 = request.GET.get("param3")  # GETパラメータ3
        logger.debug(param1 + param2 + param3)
        return HttpResponse(param1 + param2 + param3)

    elif request.method == 'POST':  # POSTの処理
        data1 = request.POST.get("input_data")  # POSTで渡された値
        logger.debug(data1)
        return HttpResponse(data1)

def exec_another_ajax(request, pk):

    if request.method == 'POST':  # POSTの処理
        data1 = request.POST.get("input_data")  # POSTで渡された値
        logger.debug(data1)
        return HttpResponse('ボタン２が押されました！')

sample/templates/sample/detail.html
{% extends 'base.html' %}

{% block content %}

    <section class="col-lg-8 offset-lg-2">
        <h1>{{ object.name }}</h1>
        {{ object.memo|linebreaksbr }}

        <hr>

        <!-- GET -->
        <button id="button1" type="button">GETボタン</button>
        <div id="resultGET"></div>

        <hr>

        <!-- POST -->
        <form id="form_button1" action="{% url 'sample:exec' object.pk %}" method="POST">
            {% csrf_token %}
            <input type="text" name="input_data" value="POSTのデータ">
            <input class="btn" type="submit" value="POSTボタン">
        </form>
        <div id="resultPOST"></div>

        <hr>

        <!-- POST(ボタン２つの処理切り分け) -->
        <form id="form_button2" action="{% url 'sample:exec' object.pk %}" method="POST">
            {% csrf_token %}
            <input type="text" name="input_data" value="処理の切り分け">
            <button class="btn btn-success" type="submit" value="button1" id="button31">ボタン1</button>
            <button class="btn btn-success" type="submit" value="button2" id="button32">ボタン2</button>
        </form>
        <div id="resultPOSTbutton2"></div>

        <script>
            $('#button1').on('click', function(){
                $('#resultGET').text('通信中...');
                // Ajax通信を開始
                $.ajax({
                    url: "{% url 'sample:exec' object.pk %}",
                    method: "GET",
                    // プレーンテキストを受信（他にはhtml、xml、script、json、jsonp等）
                    dataType: 'text',
                    // リクエストパラメータ「?param1=いろはに&param2=ほへと&param3=ちりぬるを」
                    data: {
                        param1: 'いろはに',
                        param2: 'ほへと',
                        param3: 'ちりぬるを '
                    },
                    timeout: 5000,
                })
                .done(function(data) {
                    // 通信成功時の処理を記述
                    $('#resultGET').text('GET処理成功：' + data);
                })
                .fail(function() {
                    // 通信失敗時の処理を記述
                    $('#resultGET').text('GET処理失敗.');
                });
            })

            $("#form_button1").submit( function(event) {
                event.preventDefault();
                var form = $(this);
                $('#resultPOST').text('通信中...');
                // Ajax通信を開始
                $.ajax({
                     url: form.prop("action"),
                     method: form.prop("method"),
                     data: form.serialize(),
                     timeout: 5000,
                     dataType: "text",
                })
                .done( function(data) {
                    // 通信成功時の処理を記述
                    $('#resultPOST').text('POST処理成功：' + data);
                })
                .fail(function() {
                    // 通信失敗時の処理を記述
                    $('#resultPOST').text('POST処理失敗.');
                });
            });

            $(function(){

                // フォームにtype="hidden"のinput要素を追加
                $('#form_button2').append('<input name="key" type="hidden" value="" />');

                // ボタンクリック時、type="hidden"のinput要素に自分の値を設定
                $("#button31, #button32").click(function(){
                    $('input[name=key]').val($(this).val());
                });

                $('#form_button2').submit( function(event) {

                    event.preventDefault();
                    var form = $(this);

                    // 押されたボタンによる切り分け
                    var action_url = form.prop("action");
                    if($('input[name=key]').val() == 'button2'){
                        action_url = "{% url 'sample:exec_another' object.pk %}";
                    }

                    $.ajax({
                         url: action_url,
                         method: form.prop("method"),
                         data: form.serialize(),
                         timeout: 10000,
                         dataType: "text",
                    })
                    .done( function(data) {
                        // 通信成功時の処理を記述
                        $('#resultPOSTbutton2').text('POST処理成功：' + data);
                    })
                    .fail(function() {
                        // 通信失敗時の処理を記述
                        $('#resultPOSTbutton2').text('POST処理失敗.');
                    })
                });
            });

        </script>

        <p><a href="javascript:history.back()">&lt; Back</a></p>
    </section>

{% endblock %}

sample/templates/sample/index.html
{% extends 'base.html' %}

{% block content %}

<section class="col-lg-8 offset-lg-2">

    <h1>My Locations</h1>
    <ul>
        {% for location in object_list %}
        <li>
            <h2><a href="{% url 'sample:detail' location.pk %}">{{ location.name }}</a></h2>
            <p>{{ location.memo }}</p>
        </li>
        {% empty %}
        <li class="no-post">
            <p>No location yet.</p>
        {% endfor %}
    </ul>
</section>

{% if is_paginated %}
<section class="pagination">
    <ul>
        <li>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">&lt;&lt; Prev</a>
            {% else %}
            &lt;&lt; Prev
            {% endif %}
        </li>
        <li>
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next &gt;&gt;</a>
            {% else %}
            Next &gt;&gt;
            {% endif %}
        </li>
    </ul>
</section>
{% endif %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- bootstrap4 -->
        {% load bootstrap4 %}
        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
        <!-- bootstrap4 -->

        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">

        <script type="text/javascript">
            $(function() {
                var topBtn = $('#page-top');
                topBtn.hide();
                //スクロールが500に達したらボタン表示
                $(window).scroll(function () {
                    if ($(this).scrollTop() > 500) {
                        topBtn.fadeIn();
                    } else {
                        topBtn.fadeOut();
                    }
                });
                //スクロールしてトップ
                topBtn.click(function () {
                    $('body,html').animate({
                        scrollTop: 0
                    }, 500);
                    return false;
                });
            });
        </script>

        <title>{% block title %}Sample{% endblock %}</title>
    </head>
    <body>

        <!-- ナビゲーションバーの設定 -->
        <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'sample:index' %}">Sample</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'sample:index' %}">温室一覧</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
         <main>
            {% block content %}
            {% endblock %}
        </main>
        <p id="page-top"><a href="#">PAGE TOP</a></p>
            <footer class="py-4 bg-dark">
                <div class="container text-center">
                    <p class="text-light"><small>Copyright &copy;2019 Sample, All Rights Reserved.</small></p>
                </div>
            </footer>
    </body>
</html>